import { jsPDF } from "jspdf"
import { format } from "date-fns"
import { tr } from "date-fns/locale"

// AutoTable'ı require ile yükleyelim
const autoTable = require('jspdf-autotable').default

// Modern color palette
const COLORS = {
  primary: "#10b981", // emerald-500
  secondary: "#0d9488", // teal-600
  accent: "#3b82f6", // blue-500
  danger: "#ef4444", // red-500
  warning: "#f59e0b", // amber-500
  dark: "#1f2937", // gray-800
  light: "#f3f4f6", // gray-100
  white: "#ffffff",
  text: {
    primary: "#111827", // gray-900
    secondary: "#6b7280", // gray-500
    light: "#9ca3af", // gray-400
  },
  background: {
    primary: "#ffffff",
    secondary: "#f9fafb", // gray-50
    accent: "#f0fdf4", // emerald-50
  }
}

// Typography settings
const FONTS = {
  title: { size: 24, style: "bold" },
  heading: { size: 18, style: "bold" },
  subheading: { size: 14, style: "bold" },
  body: { size: 11, style: "normal" },
  small: { size: 9, style: "normal" },
}

// Layout constants
const MARGIN = 20
const PAGE_WIDTH = 210 // A4 width in mm
const PAGE_HEIGHT = 297 // A4 height in mm
const CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2)

// Helper functions
const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat("tr-TR", {
    style: "currency",
    currency: "TRY",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

const formatPercent = (value: number): string => {
  return `%${value.toFixed(1)}`
}

const formatDate = (date: string | Date): string => {
  try {
    const dateObj = typeof date === 'string' ? new Date(date) : date
    return format(dateObj, "dd MMMM yyyy", { locale: tr })
  } catch {
    return "-"
  }
}

// Modern header design
const drawHeader = (doc: jsPDF, title: string, subtitle?: string) => {
  // Header background
  doc.setFillColor(COLORS.primary)
  doc.rect(0, 0, PAGE_WIDTH, 40, "F")
  
  // Logo area
  doc.setFillColor(COLORS.white)
  doc.circle(MARGIN + 15, 20, 12, "F")
  
  // Logo text
  doc.setTextColor(COLORS.primary)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(10)
  doc.text("KREDI", MARGIN + 15, 18, { align: "center" })
  doc.setFontSize(8)
  doc.text("TAKIP", MARGIN + 15, 23, { align: "center" })
  
  // Title
  doc.setTextColor(COLORS.white)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(FONTS.title.size)
  doc.text(title, MARGIN + 35, 20)
  
  if (subtitle) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(FONTS.body.size)
    doc.text(subtitle, MARGIN + 35, 28)
  }
  
  // Date
  doc.setFontSize(FONTS.small.size)
  doc.text(formatDate(new Date()), PAGE_WIDTH - MARGIN, 20, { align: "right" })
  
  return 45 // Return Y position after header
}

// Modern footer design
const drawFooter = (doc: jsPDF, pageNumber: number, totalPages: number) => {
  const y = PAGE_HEIGHT - 15
  
  // Footer line
  doc.setDrawColor(COLORS.light)
  doc.setLineWidth(0.5)
  doc.line(MARGIN, y - 5, PAGE_WIDTH - MARGIN, y - 5)
  
  // Footer text
  doc.setFont("helvetica", "normal")
  doc.setFontSize(FONTS.small.size)
  doc.setTextColor(COLORS.text.secondary)
  
  // Left: Generated by
  doc.text("KrediTakip AI ile oluşturuldu", MARGIN, y)
  
  // Center: Timestamp
  const timestamp = format(new Date(), "dd.MM.yyyy HH:mm")
  doc.text(timestamp, PAGE_WIDTH / 2, y, { align: "center" })
  
  // Right: Page number
  doc.text(`Sayfa ${pageNumber} / ${totalPages}`, PAGE_WIDTH - MARGIN, y, { align: "right" })
}

// Draw metric card
const drawMetricCard = (
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  height: number,
  title: string,
  value: string,
  subtitle?: string,
  color: string = COLORS.primary
) => {
  // Card background
  doc.setFillColor(COLORS.background.secondary)
  doc.roundedRect(x, y, width, height, 3, 3, "F")
  
  // Accent line
  doc.setFillColor(color)
  doc.rect(x, y, 4, height, "F")
  
  // Title
  doc.setFont("helvetica", "normal")
  doc.setFontSize(FONTS.small.size)
  doc.setTextColor(COLORS.text.secondary)
  doc.text(title, x + 8, y + 8)
  
  // Value
  doc.setFont("helvetica", "bold")
  doc.setFontSize(FONTS.heading.size)
  doc.setTextColor(COLORS.text.primary)
  doc.text(value, x + 8, y + 20)
  
  // Subtitle
  if (subtitle) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(FONTS.small.size)
    doc.setTextColor(COLORS.text.secondary)
    doc.text(subtitle, x + 8, y + 28)
  }
}

// Draw section header
const drawSectionHeader = (doc: jsPDF, title: string, y: number): number => {
  doc.setFont("helvetica", "bold")
  doc.setFontSize(FONTS.heading.size)
  doc.setTextColor(COLORS.text.primary)
  doc.text(title, MARGIN, y)
  
  // Underline
  doc.setDrawColor(COLORS.primary)
  doc.setLineWidth(2)
  doc.line(MARGIN, y + 2, MARGIN + 40, y + 2)
  
  return y + 15
}

// Main PDF generation function
export const generatePDFReport = (reportData: any) => {
  const doc = new jsPDF("p", "mm", "a4")
  let currentY = 0
  let pageNumber = 1
  const totalPages = 3 // We'll calculate this properly later
  
  // Page 1: Executive Summary
  currentY = drawHeader(doc, "Finansal Durum Raporu", "Detaylı Analiz ve Öneriler")
  
  // Summary metrics
  currentY = drawSectionHeader(doc, "Genel Özet", currentY)
  
  const metricsPerRow = 3
  const metricWidth = (CONTENT_WIDTH - 10) / metricsPerRow
  const metricHeight = 35
  
  const summaryMetrics = [
    {
      title: "Toplam Borç",
      value: formatCurrency(reportData.totalDebt || 0),
      subtitle: `${reportData.totalCredits || 0} kredi`,
      color: COLORS.danger
    },
    {
      title: "Aylık Ödeme",
      value: formatCurrency(reportData.monthlyPayment || 0),
      subtitle: "toplam ödeme",
      color: COLORS.warning
    },
    {
      title: "Aktif Kredi",
      value: (reportData.activeCredits || 0).toString(),
      subtitle: "kredi hesabı",
      color: COLORS.primary
    }
  ]
  
  summaryMetrics.forEach((metric, index) => {
    const col = index % metricsPerRow
    const row = Math.floor(index / metricsPerRow)
    const x = MARGIN + col * (metricWidth + 5)
    const y = currentY + row * (metricHeight + 5)
    
    drawMetricCard(doc, x, y, metricWidth, metricHeight, metric.title, metric.value, metric.subtitle, metric.color)
  })
  
  currentY += metricHeight + 20
  
  // Credits table
  if (reportData.credits && reportData.credits.length > 0) {
    currentY = drawSectionHeader(doc, "Kredi Detayları", currentY)
    
    const tableData = reportData.credits.map((credit: any) => [
      credit.bankName || "-",
      credit.creditType || "-",
      formatCurrency(credit.remainingDebt || 0),
      formatCurrency(credit.monthlyPayment || 0),
      `%${(credit.interestRate || 0).toFixed(2)}`
    ])
    
    autoTable(doc, {
      startY: currentY,
      head: [["Banka", "Kredi Türü", "Kalan Borç", "Aylık Ödeme", "Faiz Oranı"]],
      body: tableData,
      theme: "grid",
      headStyles: {
        fillColor: COLORS.primary,
        textColor: COLORS.white,
        fontSize: FONTS.body.size,
        fontStyle: "bold"
      },
      bodyStyles: {
        fontSize: FONTS.body.size,
        textColor: COLORS.text.primary
      },
      alternateRowStyles: {
        fillColor: COLORS.background.secondary
      },
      margin: { left: MARGIN, right: MARGIN }
    })
    
    currentY = (doc as any).lastAutoTable.finalY + 15
  }
  
  // Add footer
  drawFooter(doc, pageNumber, totalPages)
  
  // Page 2: Payment History
  if (reportData.payments && reportData.payments.length > 0) {
    doc.addPage()
    pageNumber++
    currentY = drawHeader(doc, "Ödeme Geçmişi", "Son dönem ödemeleri")
    
    currentY = drawSectionHeader(doc, "Ödeme Detayları", currentY)
    
    const paymentData = reportData.payments.slice(0, 15).map((payment: any) => [
      formatDate(payment.date),
      payment.bankName || "-",
      formatCurrency(payment.amount || 0),
      payment.status === "paid" ? "Ödendi" : payment.status === "pending" ? "Beklemede" : "Gecikmiş"
    ])
    
    autoTable(doc, {
      startY: currentY,
      head: [["Tarih", "Banka", "Tutar", "Durum"]],
      body: paymentData,
      theme: "grid",
      headStyles: {
        fillColor: COLORS.secondary,
        textColor: COLORS.white,
        fontSize: FONTS.body.size,
        fontStyle: "bold"
      },
      bodyStyles: {
        fontSize: FONTS.body.size,
        textColor: COLORS.text.primary
      },
      alternateRowStyles: {
        fillColor: COLORS.background.secondary
      },
      didDrawCell: (data: any) => {
        // Color code status column
        if (data.column.index === 3 && data.cell.section === "body") {
          const status = data.cell.text[0]
          if (status === "Ödendi") {
            doc.setTextColor(COLORS.primary)
          } else if (status === "Gecikmiş") {
            doc.setTextColor(COLORS.danger)
          } else {
            doc.setTextColor(COLORS.warning)
          }
          doc.text(status, data.cell.x + 2, data.cell.y + data.cell.height / 2 + 1)
        }
      },
      margin: { left: MARGIN, right: MARGIN }
    })
    
    drawFooter(doc, pageNumber, totalPages)
  }
  
  // Page 3: Credit Cards
  if (reportData.creditCards && reportData.creditCards.length > 0) {
    doc.addPage()
    pageNumber++
    currentY = drawHeader(doc, "Kredi Kartları", "Kart kullanım detayları")
    
    currentY = drawSectionHeader(doc, "Kart Bilgileri", currentY)
    
    const cardData = reportData.creditCards.map((card: any) => [
      card.bankName || "-",
      formatCurrency(card.creditLimit || 0),
      formatCurrency(card.currentDebt || 0),
      `%${(card.utilizationRate || 0).toFixed(1)}`
    ])
    
    autoTable(doc, {
      startY: currentY,
      head: [["Banka", "Limit", "Güncel Borç", "Kullanım"]],
      body: cardData,
      theme: "grid",
      headStyles: {
        fillColor: COLORS.accent,
        textColor: COLORS.white,
        fontSize: FONTS.body.size,
        fontStyle: "bold"
      },
      bodyStyles: {
        fontSize: FONTS.body.size,
        textColor: COLORS.text.primary
      },
      alternateRowStyles: {
        fillColor: COLORS.background.secondary
      },
      didDrawCell: (data: any) => {
        // Color code utilization column
        if (data.column.index === 3 && data.cell.section === "body") {
          const utilizationText = data.cell.text[0]
          const utilization = parseFloat(utilizationText.replace("%", ""))
          
          if (utilization > 80) {
            doc.setTextColor(COLORS.danger)
          } else if (utilization > 50) {
            doc.setTextColor(COLORS.warning)
          } else {
            doc.setTextColor(COLORS.primary)
          }
          doc.text(utilizationText, data.cell.x + 2, data.cell.y + data.cell.height / 2 + 1)
        }
      },
      margin: { left: MARGIN, right: MARGIN }
    })
    
    currentY = (doc as any).lastAutoTable.finalY + 20
    
    // Recommendations section
    currentY = drawSectionHeader(doc, "Öneriler", currentY)
    
    doc.setFont("helvetica", "normal")
    doc.setFontSize(FONTS.body.size)
    doc.setTextColor(COLORS.text.primary)
    
    const recommendations = [
      "• Kredi kartı borcunuzu minimize ederek faiz ödemelerini azaltın",
      "• Aylık ödemelerinizi zamanında yaparak kredi puanınızı iyileştirin",
      "• Yüksek faizli kredileri öncelikli olarak kapatmayı hedefleyin",
      "• Acil durum fonu oluşturarak beklenmedik harcamalara hazırlıklı olun"
    ]
    
    recommendations.forEach((rec, index) => {
      doc.text(rec, MARGIN, currentY + (index * 8))
    })
    
    drawFooter(doc, pageNumber, totalPages)
  }
  
  // Save the PDF
  const fileName = `kredi-raporu-${format(new Date(), "yyyy-MM-dd-HHmm")}.pdf`
  doc.save(fileName)
}

// Enhanced PDF generation with charts and graphs
export const generateEnhancedPDFReport = generatePDFReport