import { jsPDF } from "jspdf"
import { format } from "date-fns"
import { tr } from "date-fns/locale"

// Modern color palette
const COLORS = {
  primary: "#10b981", // emerald-500
  secondary: "#0d9488", // teal-600
  accent: "#3b82f6", // blue-500
  danger: "#ef4444", // red-500
  warning: "#f59e0b", // amber-500
  dark: "#1f2937", // gray-800
  light: "#f3f4f6", // gray-100
  white: "#ffffff",
  text: {
    primary: "#111827", // gray-900
    secondary: "#6b7280", // gray-500
    light: "#9ca3af", // gray-400
  },
  background: {
    primary: "#ffffff",
    secondary: "#f9fafb", // gray-50
    accent: "#f0fdf4", // emerald-50
  }
}

// Typography settings
const FONTS = {
  title: { size: 24, style: "bold" },
  heading: { size: 18, style: "bold" },
  subheading: { size: 14, style: "bold" },
  body: { size: 11, style: "normal" },
  small: { size: 9, style: "normal" },
}

// Layout constants
const MARGIN = 20
const PAGE_WIDTH = 210 // A4 width in mm
const PAGE_HEIGHT = 297 // A4 height in mm
const CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2)

// Helper functions
const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat("tr-TR", {
    style: "currency",
    currency: "TRY",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

const formatPercent = (value: number): string => {
  return `%${value.toFixed(1)}`
}

const formatDate = (date: string | Date): string => {
  try {
    const dateObj = typeof date === 'string' ? new Date(date) : date
    return format(dateObj, "dd MMMM yyyy", { locale: tr })
  } catch {
    return "-"
  }
}

// Modern header design
const drawHeader = (doc: jsPDF, title: string, subtitle?: string) => {
  // Header background gradient effect
  doc.setFillColor(16, 185, 129) // emerald-500
  doc.rect(0, 0, PAGE_WIDTH, 40, "F")
  
  doc.setFillColor(13, 148, 136) // teal-600
  doc.rect(0, 35, PAGE_WIDTH, 5, "F")
  
  // Logo area
  doc.setFillColor(255, 255, 255)
  doc.circle(MARGIN + 15, 20, 12, "F")
  
  // Logo text
  doc.setTextColor(16, 185, 129)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(10)
  doc.text("KREDI", MARGIN + 15, 18, { align: "center" })
  doc.setFontSize(8)
  doc.text("TAKIP", MARGIN + 15, 23, { align: "center" })
  
  // Title
  doc.setTextColor(255, 255, 255)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(FONTS.title.size)
  doc.text(title, MARGIN + 35, 20)
  
  if (subtitle) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(FONTS.body.size)
    doc.text(subtitle, MARGIN + 35, 28)
  }
  
  // Date
  doc.setFontSize(FONTS.small.size)
  doc.text(formatDate(new Date()), PAGE_WIDTH - MARGIN, 20, { align: "right" })
  
  return 50 // Return Y position after header
}

// Modern footer design
const drawFooter = (doc: jsPDF, pageNumber: number, totalPages: number) => {
  const y = PAGE_HEIGHT - 15
  
  // Footer line
  doc.setDrawColor(243, 244, 246) // gray-100
  doc.setLineWidth(0.5)
  doc.line(MARGIN, y - 5, PAGE_WIDTH - MARGIN, y - 5)
  
  // Footer text
  doc.setFont("helvetica", "normal")
  doc.setFontSize(FONTS.small.size)
  doc.setTextColor(107, 114, 128) // gray-500
  
  // Left: Generated by
  doc.text("KrediTakip AI ile oluşturuldu", MARGIN, y)
  
  // Center: Timestamp
  const timestamp = format(new Date(), "dd.MM.yyyy HH:mm")
  doc.text(timestamp, PAGE_WIDTH / 2, y, { align: "center" })
  
  // Right: Page number
  doc.text(`Sayfa ${pageNumber} / ${totalPages}`, PAGE_WIDTH - MARGIN, y, { align: "right" })
}

// Draw metric card
const drawMetricCard = (
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  height: number,
  title: string,
  value: string,
  subtitle?: string,
  color: string = COLORS.primary
) => {
  // Card background
  doc.setFillColor(249, 250, 251) // gray-50
  doc.rect(x, y, width, height, "F")
  
  // Card border
  doc.setDrawColor(229, 231, 235) // gray-200
  doc.setLineWidth(0.5)
  doc.rect(x, y, width, height, "S")
  
  // Accent line
  const [r, g, b] = hexToRgb(color)
  doc.setFillColor(r, g, b)
  doc.rect(x, y, 4, height, "F")
  
  // Title
  doc.setFont("helvetica", "normal")
  doc.setFontSize(FONTS.small.size)
  doc.setTextColor(107, 114, 128) // gray-500
  doc.text(title, x + 8, y + 10)
  
  // Value
  doc.setFont("helvetica", "bold")
  doc.setFontSize(FONTS.heading.size)
  doc.setTextColor(17, 24, 39) // gray-900
  doc.text(value, x + 8, y + 25)
  
  // Subtitle
  if (subtitle) {
    doc.setFont("helvetica", "normal")
    doc.setFontSize(FONTS.small.size)
    doc.setTextColor(156, 163, 175) // gray-400
    doc.text(subtitle, x + 8, y + 33)
  }
}

// Helper function to convert hex to RGB
const hexToRgb = (hex: string): [number, number, number] => {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return result 
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [107, 114, 128] // gray-500 as fallback
}

// Draw section header
const drawSectionHeader = (doc: jsPDF, title: string, y: number): number => {
  doc.setFont("helvetica", "bold")
  doc.setFontSize(FONTS.heading.size)
  doc.setTextColor(17, 24, 39) // gray-900
  doc.text(title, MARGIN, y)
  
  // Underline
  doc.setDrawColor(16, 185, 129) // emerald-500
  doc.setLineWidth(2)
  doc.line(MARGIN, y + 2, MARGIN + 40, y + 2)
  
  return y + 15
}

// Simple table drawing function
const drawTable = (
  doc: jsPDF,
  headers: string[],
  data: string[][],
  x: number,
  y: number,
  columnWidths: number[]
) => {
  const rowHeight = 10
  const headerHeight = 12
  let currentY = y
  
  // Table header background
  doc.setFillColor(16, 185, 129) // emerald-500
  doc.rect(x, currentY, columnWidths.reduce((a, b) => a + b, 0), headerHeight, "F")
  
  // Header text
  doc.setFont("helvetica", "bold")
  doc.setFontSize(FONTS.body.size)
  doc.setTextColor(255, 255, 255)
  
  let currentX = x
  headers.forEach((header, i) => {
    doc.text(header, currentX + 3, currentY + 8)
    currentX += columnWidths[i]
  })
  
  currentY += headerHeight
  
  // Table data
  doc.setFont("helvetica", "normal")
  doc.setTextColor(17, 24, 39) // gray-900
  
  data.forEach((row, rowIndex) => {
    // Alternate row background
    if (rowIndex % 2 === 1) {
      doc.setFillColor(249, 250, 251) // gray-50
      doc.rect(x, currentY, columnWidths.reduce((a, b) => a + b, 0), rowHeight, "F")
    }
    
    currentX = x
    row.forEach((cell, cellIndex) => {
      doc.text(cell, currentX + 3, currentY + 7)
      currentX += columnWidths[cellIndex]
    })
    
    currentY += rowHeight
  })
  
  // Table border
  doc.setDrawColor(229, 231, 235) // gray-200
  doc.setLineWidth(0.5)
  doc.rect(x, y, columnWidths.reduce((a, b) => a + b, 0), currentY - y, "S")
  
  return currentY
}

// Main PDF generation function
export const generatePDFReport = (reportData: any) => {
  const doc = new jsPDF("p", "mm", "a4")
  let currentY = 0
  let pageNumber = 1
  const totalPages = 3 // We'll calculate this properly later
  
  // Page 1: Executive Summary
  currentY = drawHeader(doc, "Finansal Durum Raporu", "Detaylı Analiz ve Öneriler")
  
  // Summary metrics
  currentY = drawSectionHeader(doc, "Genel Özet", currentY)
  
  const metricsPerRow = 3
  const metricWidth = (CONTENT_WIDTH - 10) / metricsPerRow
  const metricHeight = 38
  
  const summaryMetrics = [
    {
      title: "Toplam Borç",
      value: formatCurrency(reportData.totalDebt || 0),
      subtitle: `${reportData.totalCredits || 0} kredi`,
      color: COLORS.danger
    },
    {
      title: "Aylık Ödeme",
      value: formatCurrency(reportData.monthlyPayment || 0),
      subtitle: "toplam ödeme",
      color: COLORS.warning
    },
    {
      title: "Aktif Kredi",
      value: (reportData.activeCredits || 0).toString(),
      subtitle: "kredi hesabı",
      color: COLORS.primary
    }
  ]
  
  summaryMetrics.forEach((metric, index) => {
    const col = index % metricsPerRow
    const row = Math.floor(index / metricsPerRow)
    const x = MARGIN + col * (metricWidth + 5)
    const y = currentY + row * (metricHeight + 5)
    
    drawMetricCard(doc, x, y, metricWidth, metricHeight, metric.title, metric.value, metric.subtitle, metric.color)
  })
  
  currentY += metricHeight + 20
  
  // Credits table
  if (reportData.credits && reportData.credits.length > 0) {
    currentY = drawSectionHeader(doc, "Kredi Detayları", currentY)
    
    const headers = ["Banka", "Kredi Türü", "Kalan Borç", "Aylık Ödeme", "Faiz"]
    const columnWidths = [40, 35, 35, 35, 25]
    
    const tableData = reportData.credits.slice(0, 10).map((credit: any) => [
      (credit.bankName || "-").substring(0, 20),
      (credit.creditType || "-").substring(0, 18),
      formatCurrency(credit.remainingDebt || 0),
      formatCurrency(credit.monthlyPayment || 0),
      `%${(credit.interestRate || 0).toFixed(2)}`
    ])
    
    currentY = drawTable(doc, headers, tableData, MARGIN, currentY, columnWidths)
    currentY += 15
  }
  
  // Add footer
  drawFooter(doc, pageNumber, totalPages)
  
  // Page 2: Payment History
  if (reportData.payments && reportData.payments.length > 0) {
    doc.addPage()
    pageNumber++
    currentY = drawHeader(doc, "Ödeme Geçmişi", "Son dönem ödemeleri")
    
    currentY = drawSectionHeader(doc, "Ödeme Detayları", currentY)
    
    const headers = ["Tarih", "Banka", "Tutar", "Durum"]
    const columnWidths = [35, 50, 45, 40]
    
    const paymentData = reportData.payments.slice(0, 20).map((payment: any) => [
      formatDate(payment.date).substring(0, 15),
      (payment.bankName || "-").substring(0, 25),
      formatCurrency(payment.amount || 0),
      payment.status === "paid" ? "Ödendi" : payment.status === "pending" ? "Beklemede" : "Gecikmiş"
    ])
    
    currentY = drawTable(doc, headers, paymentData, MARGIN, currentY, columnWidths)
    
    drawFooter(doc, pageNumber, totalPages)
  }
  
  // Page 3: Recommendations
  doc.addPage()
  pageNumber++
  currentY = drawHeader(doc, "Öneriler ve Analizler", "AI destekli finansal öneriler")
  
  currentY = drawSectionHeader(doc, "Önerilerimiz", currentY)
  
  doc.setFont("helvetica", "normal")
  doc.setFontSize(FONTS.body.size)
  doc.setTextColor(17, 24, 39) // gray-900
  
  const recommendations = [
    "• Kredi kartı borcunuzu minimize ederek faiz ödemelerini azaltın",
    "• Aylık ödemelerinizi zamanında yaparak kredi puanınızı iyileştirin",
    "• Yüksek faizli kredileri öncelikli olarak kapatmayı hedefleyin",
    "• Acil durum fonu oluşturarak beklenmedik harcamalara hazırlıklı olun",
    "• Kredi kullanım oranınızı %30'un altında tutmaya çalışın",
    "• Düzenli bütçe takibi yaparak harcamalarınızı kontrol altında tutun"
  ]
  
  recommendations.forEach((rec, index) => {
    doc.text(rec, MARGIN, currentY + (index * 10))
  })
  
  currentY += recommendations.length * 10 + 20
  
  // Action items box
  doc.setFillColor(240, 253, 244) // emerald-50
  doc.rect(MARGIN, currentY, CONTENT_WIDTH, 60, "F")
  
  doc.setDrawColor(16, 185, 129) // emerald-500
  doc.setLineWidth(1)
  doc.rect(MARGIN, currentY, CONTENT_WIDTH, 60, "S")
  
  doc.setFont("helvetica", "bold")
  doc.setFontSize(FONTS.subheading.size)
  doc.setTextColor(16, 185, 129) // emerald-500
  doc.text("Hemen Yapılması Gerekenler", MARGIN + 10, currentY + 12)
  
  doc.setFont("helvetica", "normal")
  doc.setFontSize(FONTS.body.size)
  doc.setTextColor(17, 24, 39) // gray-900
  
  const actions = [
    "1. En yüksek faizli kredinizi belirleyin ve ekstra ödemeler yapın",
    "2. Kredi kartı borcunuzu minimum ödeme tutarının üzerinde ödeyin",
    "3. Gelecek 3 ayın ödeme planını takvime işaretleyin",
    "4. Aylık gelir-gider tablosu oluşturun"
  ]
  
  actions.forEach((action, index) => {
    doc.text(action, MARGIN + 10, currentY + 25 + (index * 8))
  })
  
  drawFooter(doc, pageNumber, totalPages)
  
  // Save the PDF
  const fileName = `kredi-raporu-${format(new Date(), "yyyy-MM-dd-HHmm")}.pdf`
  doc.save(fileName)
}